# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaces\MainWindow\ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1001, 557)
        MainWindow.setAcceptDrops(False)
        MainWindow.setStyleSheet("#centralwidget {\n"
"    border-radius: 20px;\n"
"\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(251, 251, 255, 255), stop:1 rgba(234, 234, 237, 255));\n"
"}\n"
"\n"
"QLabel {\n"
"    font: 81 12pt \"Montserrat ExtraBold\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.explorerFrame = QtWidgets.QFrame(self.centralwidget)
        self.explorerFrame.setMinimumSize(QtCore.QSize(200, 0))
        self.explorerFrame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.explorerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.explorerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.explorerFrame.setObjectName("explorerFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.explorerFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(25)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.logoFrame = QtWidgets.QFrame(self.explorerFrame)
        self.logoFrame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.logoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logoFrame.setObjectName("logoFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.logoFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logoPixmap = QtWidgets.QLabel(self.logoFrame)
        self.logoPixmap.setMinimumSize(QtCore.QSize(36, 36))
        self.logoPixmap.setMaximumSize(QtCore.QSize(36, 36))
        self.logoPixmap.setText("")
        self.logoPixmap.setPixmap(QtGui.QPixmap(":/Icons/Icons/sgraphy.png"))
        self.logoPixmap.setScaledContents(True)
        self.logoPixmap.setObjectName("logoPixmap")
        self.horizontalLayout_2.addWidget(self.logoPixmap)
        self.logoText = QtWidgets.QLabel(self.logoFrame)
        font = QtGui.QFont()
        font.setFamily("Montserrat ExtraBold")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.logoText.setFont(font)
        self.logoText.setStyleSheet("#logoText {\n"
"    font: 81 11pt \"Montserrat ExtraBold\";\n"
"}")
        self.logoText.setObjectName("logoText")
        self.horizontalLayout_2.addWidget(self.logoText)
        self.verticalLayout.addWidget(self.logoFrame)
        self.buttonsFrame = QtWidgets.QFrame(self.explorerFrame)
        self.buttonsFrame.setStyleSheet("QRadioButton {\n"
"    background: rgba(0,0,0,0);\n"
"    border-radius: 10px;\n"
"\n"
"    color: rgb(150, 150, 150);\n"
"\n"
"    font: 81 12pt \"Montserrat ExtraBold\";\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QRadioButton:checked {\n"
"    color: rgba(255, 255, 255, 255);\n"
"    background: rgba(0,142,255,255);\n"
"}")
        self.buttonsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttonsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonsFrame.setObjectName("buttonsFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.buttonsFrame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.imagesButton = QtWidgets.QRadioButton(self.buttonsFrame)
        self.imagesButton.setMinimumSize(QtCore.QSize(0, 40))
        self.imagesButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.imagesButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.imagesButton.setStyleSheet("spacing: 30px;")
        self.imagesButton.setChecked(True)
        self.imagesButton.setAutoExclusive(True)
        self.imagesButton.setObjectName("imagesButton")
        self.verticalLayout_2.addWidget(self.imagesButton)
        self.musicButton = QtWidgets.QRadioButton(self.buttonsFrame)
        self.musicButton.setMinimumSize(QtCore.QSize(0, 40))
        self.musicButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.musicButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.musicButton.setStyleSheet("spacing: 55px;")
        self.musicButton.setAutoExclusive(True)
        self.musicButton.setObjectName("musicButton")
        self.verticalLayout_2.addWidget(self.musicButton)
        self.docsButton = QtWidgets.QRadioButton(self.buttonsFrame)
        self.docsButton.setMinimumSize(QtCore.QSize(0, 40))
        self.docsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.docsButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.docsButton.setStyleSheet("spacing: 40px;")
        self.docsButton.setAutoExclusive(True)
        self.docsButton.setObjectName("docsButton")
        self.verticalLayout_2.addWidget(self.docsButton)
        self.textButton = QtWidgets.QRadioButton(self.buttonsFrame)
        self.textButton.setMinimumSize(QtCore.QSize(0, 40))
        self.textButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.textButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textButton.setStyleSheet("spacing: 10px;")
        self.textButton.setAutoExclusive(True)
        self.textButton.setObjectName("textButton")
        self.verticalLayout_2.addWidget(self.textButton)
        self.otherButton = QtWidgets.QRadioButton(self.buttonsFrame)
        self.otherButton.setMinimumSize(QtCore.QSize(0, 40))
        self.otherButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.otherButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.otherButton.setStyleSheet("spacing: 55px;")
        self.otherButton.setAutoExclusive(True)
        self.otherButton.setObjectName("otherButton")
        self.verticalLayout_2.addWidget(self.otherButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.buttonsFrame)
        self.horizontalLayout.addWidget(self.explorerFrame)
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setStyleSheet("#mainTabs::pane {\n"
"    border: none;\n"
"    box-shadow: none;\n"
"    outline: none;\n"
"}\n"
"\n"
"#mainTabs::tab-bar {\n"
"    width: 0; height: 0; margin: 0; padding: 0; border: none;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    border-radius: 10px;\n"
"\n"
"    font: 81 12pt \"Montserrat ExtraBold\";\n"
"\n"
"    color: rgb(150, 150, 150);\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background: rgba(0,142,255,255);\n"
"    width: 20px;\n"
"}")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.mainFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.mainFrame)
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.imagesWidget = QtWidgets.QWidget()
        self.imagesWidget.setStyleSheet("#imagePreviewFrame,\n"
"#imageDropbox,\n"
"#imagesList {\n"
"    background: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#imagePreview {\n"
"    border-radius: 5px;\n"
"    background-color: rgb(200, 200, 200);\n"
"}\n"
"")
        self.imagesWidget.setObjectName("imagesWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.imagesWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.leftImagesMenu = QtWidgets.QFrame(self.imagesWidget)
        self.leftImagesMenu.setAcceptDrops(False)
        self.leftImagesMenu.setStyleSheet("#imageDropbox {\n"
"    background: rgb(255,255,255);\n"
"\n"
"    font: 63 12pt \"Montserrat SemiBold\";\n"
"    color: rgb(150, 150, 150);\n"
"}\n"
"\n"
"#imagesList {\n"
"    font: 63 10pt \"Montserrat SemiBold\";\n"
"    color: rgb(150, 150, 150);\n"
"\n"
"    outline: 0;\n"
"}\n"
"\n"
"#imagesList:checked {\n"
"    color: rgba(255, 255, 255, 255);\n"
"    background: rgba(0,142,255,255);\n"
"}\n"
"\n"
"#imagesList::item {\n"
"    margin: 5px;\n"
"    margin-bottom: 0px;\n"
"\n"
"    min-height: 30px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#imagesList::item:selected {\n"
"    color: rgba(255, 255, 255, 255);\n"
"    background: rgba(0,142,255,255);\n"
"}\n"
"\n"
"#imagesList::item:selected:!active {\n"
"    color: rgba(255, 255, 255, 255);\n"
"    background: rgba(0,142,255,255);\n"
"}\n"
"\n"
"#imagesList::item:selected:active {\n"
"    color: rgba(255, 255, 255, 255);\n"
"    background: rgba(0,142,255,255);\n"
"}\n"
"\n"
"#imagesList::item:hover {\n"
"    color: rgba(255, 255, 255, 255);\n"
"    background: rgba(0,142,255,255);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background: rgba(0,0,0,0);\n"
"    border-radius: 10px;\n"
"\n"
"    color: rgba(255, 255, 255, 255);\n"
"    background: rgba(0,142,255,255);\n"
"\n"
"    font: 81 10pt \"Montserrat ExtraBold\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgba(255, 255, 255, 255);\n"
"    background: rgb(0, 113, 204);\n"
"}")
        self.leftImagesMenu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftImagesMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftImagesMenu.setLineWidth(0)
        self.leftImagesMenu.setObjectName("leftImagesMenu")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.leftImagesMenu)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.imageDropbox = QtWidgets.QLabel(self.leftImagesMenu)
        self.imageDropbox.setMinimumSize(QtCore.QSize(0, 70))
        self.imageDropbox.setMaximumSize(QtCore.QSize(16777215, 70))
        self.imageDropbox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.imageDropbox.setMouseTracking(False)
        self.imageDropbox.setAcceptDrops(True)
        self.imageDropbox.setAlignment(QtCore.Qt.AlignCenter)
        self.imageDropbox.setObjectName("imageDropbox")
        self.verticalLayout_5.addWidget(self.imageDropbox)
        self.addImageButton = QtWidgets.QPushButton(self.leftImagesMenu)
        self.addImageButton.setMinimumSize(QtCore.QSize(0, 40))
        self.addImageButton.setStyleSheet("")
        self.addImageButton.setObjectName("addImageButton")
        self.verticalLayout_5.addWidget(self.addImageButton)
        self.imagesList = QtWidgets.QListWidget(self.leftImagesMenu)
        self.imagesList.setMinimumSize(QtCore.QSize(0, 0))
        self.imagesList.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.imagesList.setAutoScroll(True)
        self.imagesList.setObjectName("imagesList")
        self.verticalLayout_5.addWidget(self.imagesList)
        self.horizontalLayout_3.addWidget(self.leftImagesMenu)
        self.imagePreviewFrame = QtWidgets.QFrame(self.imagesWidget)
        self.imagePreviewFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.imagePreviewFrame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.imagePreviewFrame.setStyleSheet("")
        self.imagePreviewFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imagePreviewFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imagePreviewFrame.setObjectName("imagePreviewFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.imagePreviewFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.imagePreview = QtWidgets.QLabel(self.imagePreviewFrame)
        self.imagePreview.setMinimumSize(QtCore.QSize(150, 150))
        self.imagePreview.setMaximumSize(QtCore.QSize(150, 150))
        self.imagePreview.setLineWidth(0)
        self.imagePreview.setText("")
        self.imagePreview.setScaledContents(True)
        self.imagePreview.setAlignment(QtCore.Qt.AlignCenter)
        self.imagePreview.setWordWrap(False)
        self.imagePreview.setObjectName("imagePreview")
        self.verticalLayout_3.addWidget(self.imagePreview)
        self.imageSizeText = QtWidgets.QLabel(self.imagePreviewFrame)
        self.imageSizeText.setStyleSheet("font: 63 8pt \"Montserrat SemiBold\";\n"
"color: rgb(0, 0, 0);")
        self.imageSizeText.setObjectName("imageSizeText")
        self.verticalLayout_3.addWidget(self.imageSizeText)
        self.imageWidthText = QtWidgets.QLabel(self.imagePreviewFrame)
        self.imageWidthText.setStyleSheet("font: 63 8pt \"Montserrat SemiBold\";\n"
"color: rgb(0, 0, 0);")
        self.imageWidthText.setObjectName("imageWidthText")
        self.verticalLayout_3.addWidget(self.imageWidthText)
        self.imageHeightText = QtWidgets.QLabel(self.imagePreviewFrame)
        self.imageHeightText.setStyleSheet("font: 63 8pt \"Montserrat SemiBold\";\n"
"color: rgb(0, 0, 0);")
        self.imageHeightText.setObjectName("imageHeightText")
        self.verticalLayout_3.addWidget(self.imageHeightText)
        self.keysFrame = QtWidgets.QFrame(self.imagePreviewFrame)
        self.keysFrame.setStyleSheet("QLineEdit {\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    color: rgb(100, 100, 100);\n"
"    background-color: rgb(200, 200, 200);\n"
"\n"
"    font: 63 10pt \"Montserrat SemiBold\";\n"
"}")
        self.keysFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.keysFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.keysFrame.setObjectName("keysFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.keysFrame)
        self.verticalLayout_4.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textToEncode = QtWidgets.QLineEdit(self.keysFrame)
        self.textToEncode.setMinimumSize(QtCore.QSize(0, 30))
        self.textToEncode.setAlignment(QtCore.Qt.AlignCenter)
        self.textToEncode.setReadOnly(False)
        self.textToEncode.setObjectName("textToEncode")
        self.verticalLayout_4.addWidget(self.textToEncode)
        self.secretKey = QtWidgets.QLineEdit(self.keysFrame)
        self.secretKey.setMinimumSize(QtCore.QSize(0, 30))
        self.secretKey.setAlignment(QtCore.Qt.AlignCenter)
        self.secretKey.setReadOnly(False)
        self.secretKey.setObjectName("secretKey")
        self.verticalLayout_4.addWidget(self.secretKey)
        self.verticalLayout_3.addWidget(self.keysFrame)
        self.secretKeyHelpLabel = QtWidgets.QLabel(self.imagePreviewFrame)
        self.secretKeyHelpLabel.setStyleSheet("QLabel {\n"
"    border: none;\n"
"    color: rgb(255, 100, 100);\n"
"\n"
"    font: 63 10pt \"Montserrat SemiBold\";\n"
"}")
        self.secretKeyHelpLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.secretKeyHelpLabel.setWordWrap(True)
        self.secretKeyHelpLabel.setObjectName("secretKeyHelpLabel")
        self.verticalLayout_3.addWidget(self.secretKeyHelpLabel)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.encryptionFrame = QtWidgets.QFrame(self.imagePreviewFrame)
        self.encryptionFrame.setStyleSheet("QPushButton {\n"
"    background: rgba(0,0,0,0);\n"
"    border-radius: 10px;\n"
"\n"
"    color: rgba(255, 255, 255, 255);\n"
"    background: rgba(0,142,255,255);\n"
"\n"
"    font: 81 10pt \"Montserrat ExtraBold\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgba(255, 255, 255, 255);\n"
"    background: rgb(0, 113, 204);\n"
"}")
        self.encryptionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.encryptionFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.encryptionFrame.setObjectName("encryptionFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.encryptionFrame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.decryptButton = QtWidgets.QPushButton(self.encryptionFrame)
        self.decryptButton.setMinimumSize(QtCore.QSize(0, 40))
        self.decryptButton.setObjectName("decryptButton")
        self.horizontalLayout_4.addWidget(self.decryptButton)
        self.encryptButton = QtWidgets.QPushButton(self.encryptionFrame)
        self.encryptButton.setMinimumSize(QtCore.QSize(0, 40))
        self.encryptButton.setObjectName("encryptButton")
        self.horizontalLayout_4.addWidget(self.encryptButton)
        self.verticalLayout_3.addWidget(self.encryptionFrame)
        self.horizontalLayout_3.addWidget(self.imagePreviewFrame)
        self.stackedWidget.addWidget(self.imagesWidget)
        self.musicWidget = QtWidgets.QWidget()
        self.musicWidget.setObjectName("musicWidget")
        self.stackedWidget.addWidget(self.musicWidget)
        self.docsWidget = QtWidgets.QWidget()
        self.docsWidget.setObjectName("docsWidget")
        self.stackedWidget.addWidget(self.docsWidget)
        self.textWidget = QtWidgets.QWidget()
        self.textWidget.setObjectName("textWidget")
        self.stackedWidget.addWidget(self.textWidget)
        self.otherWidget = QtWidgets.QWidget()
        self.otherWidget.setObjectName("otherWidget")
        self.stackedWidget.addWidget(self.otherWidget)
        self.gridLayout.addWidget(self.stackedWidget, 0, 2, 1, 1)
        self.horizontalLayout.addWidget(self.mainFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.logoText.setText(_translate("MainWindow", "SGraphy"))
        self.imagesButton.setText(_translate("MainWindow", "Изображения"))
        self.musicButton.setText(_translate("MainWindow", "Музыка"))
        self.docsButton.setText(_translate("MainWindow", "Документы"))
        self.textButton.setText(_translate("MainWindow", "Текстовые файлы"))
        self.otherButton.setText(_translate("MainWindow", "Другое"))
        self.imageDropbox.setText(_translate("MainWindow", "Переместите изображение для добаления"))
        self.addImageButton.setText(_translate("MainWindow", "Добавить изображение"))
        self.imageSizeText.setText(_translate("MainWindow", "Размер: Не выбрано"))
        self.imageWidthText.setText(_translate("MainWindow", "Ширина: Не выбрано"))
        self.imageHeightText.setText(_translate("MainWindow", "Высота: Не выбрано"))
        self.textToEncode.setPlaceholderText(_translate("MainWindow", "Текст для шифрования"))
        self.secretKey.setPlaceholderText(_translate("MainWindow", "Секретный ключ"))
        self.secretKeyHelpLabel.setText(_translate("MainWindow", "При зашифровке секретный ключ генерируется автоматически!"))
        self.decryptButton.setText(_translate("MainWindow", "Разшифровать"))
        self.encryptButton.setText(_translate("MainWindow", "Зашифровать"))
import MainWindow.MainWindow_rc
